CREATE TABLE USER_U(
   U_ID VARCHAR2(50) NOT NULL, 
   U_PASSWORD VARCHAR2(100) NOT NULL,
   U_NAME VARCHAR2(20) NOT NULL,
   U_EMAIL VARCHAR2(50) NOT NULL,
   U_PHONE VARCHAR2(20) NOT NULL,
   U_ENABLE CHAR(1) NOT NULL,
   U_AUTH CHAR(1) NOT NULL,
   F_NAME VARCHAR2(100),
   CONSTRAINT USER_PK PRIMARY KEY(U_ID)
);

CREATE TABLE HOSPITAL(
   H_NAME VARCHAR2(50) NOT NULL,
   H_ADDRESS VARCHAR2(100) NOT NULL,
   H_PHONE VARCHAR2(11) NOT NULL,
   H_MAIL VARCHAR2(100) NOT NULL,
   H_REGI CHAR(12) NOT NULL,
   U_ID VARCHAR2(50) NOT NULL,
   H_ENABLE CHAR(1) NOT NULL, 
   MAIN_OBJ CHAR(3) NOT NULL,
   MAIN_ANI CHAR(3) NOT NULL,
   CONSTRAINT HOSPI_PK PRIMARY KEY(H_REGI),
   CONSTRAINT HOSPI_FK FOREIGN KEY(U_ID) REFERENCES USER_U(U_ID)
);

CREATE TABLE RESERVATION(
   SEQ NUMBER NOT NULL,
   U_ID VARCHAR2(50) NOT NULL,
   H_REGI CHAR(12)   NOT NULL,
   R_STATUS CHAR(1) NOT NULL,
   R_DATE DATE NOT NULL,
   R_CONTENT VARCHAR2(1000) NOT NULL,
   CONSTRAINT RESER_PK PRIMARY KEY(SEQ),
   CONSTRAINT RESER_FK1 FOREIGN KEY(U_ID) REFERENCES USER_U(U_ID),
   CONSTRAINT RESER_FK2 FOREIGN KEY(H_REGI) REFERENCES HOSPITAL(H_REGI)
);
CREATE SEQUENCE RESERVATION_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE O_CODE (
    MAIN_OBJ    CHAR(5)   NOT NULL,
    OBJ_CODE    CHAR(30)   NOT NULL,
   CONSTRAINT O_FK PRIMARY KEY(MAIN_OBJ)
);

CREATE TABLE H_CODE_OBJ(
    H_REGI    CHAR(12)   NOT NULL,
    MAIN_OBJ    CHAR(5)   NOT NULL,
   CONSTRAINT H_OBJ_FK1 FOREIGN KEY(H_REGI) REFERENCES HOSPITAL(H_REGI),
   CONSTRAINT H_OBJ_FK2 FOREIGN KEY(MAIN_OBJ) REFERENCES O_CODE(MAIN_OBJ)
);

CREATE TABLE  OBJ  (
    MAIN_OBJ    CHAR(5)   NOT NULL,
    OBJ_DETAIL_CODE    CHAR(3),
    OBJ_CONTENT    VARCHAR2(30),
    CONSTRAINT OBJ_FK FOREIGN KEY (MAIN_OBJ) REFERENCES O_CODE(MAIN_OBJ)
);

CREATE TABLE  A_CODE  (
    MAIN_ANI    CHAR(5)   NOT NULL,
    ANI_CODE    CHAR(30)   NOT NULL,
   CONSTRAINT A_CODE_FK PRIMARY KEY(MAIN_ANI)
);

CREATE TABLE H_CODE_ANI(
    H_REGI    CHAR(12)   NOT NULL,
    MAIN_ANI    CHAR(5)   NOT NULL,
   CONSTRAINT H_ANI_FK1 FOREIGN KEY(H_REGI) REFERENCES HOSPITAL(H_REGI),
   CONSTRAINT H_ANI_FK2 FOREIGN KEY(MAIN_ANI) REFERENCES A_CODE(MAIN_ANI)
);

CREATE TABLE  ANI  (
   MAIN_ANI    CHAR(5)   NOT NULL,
   ANI_DETAIL_CODE    CHAR(3),
   ANI_CONTENT    VARCHAR(30),
   CONSTRAINT ANI_FK FOREIGN KEY (MAIN_ANI) REFERENCES A_CODE(MAIN_ANI)
);


CREATE TABLE  HONGBOARD  (
    SEQ    NUMBER   NOT NULL,
    H_REGI    CHAR(12)   NOT NULL,
    U_ID    VARCHAR2(50)   NOT NULL,
    TITLE    VARCHAR2(100)   NOT NULL,
    CONTENT    VARCHAR2(1000)   NOT NULL,
    REFER    NUMBER   NOT NULL,
    STEP    NUMBER   NOT NULL,
    DEPTH    NUMBER   NOT NULL,
    F_NAME    VARCHAR2(100),
    DELFLAG    CHAR(1)   NOT NULL,
    REGDATE    DATE   NOT NULL,
    READCOUNT    NUMBER   NOT NULL,
    CONSTRAINT HONGBO_PK PRIMARY KEY(SEQ),
     CONSTRAINT HONGBO_FK1 FOREIGN KEY(H_REGI) REFERENCES HOSPITAL(H_REGI)
);
CREATE SEQUENCE HONGBOARD_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE  POSTBOARD  (
    SEQ    NUMBER   NOT NULL,
    U_ID    VARCHAR2(50)   NOT NULL,
    TITLE    VARCHAR2(100)   NOT NULL,
    CONTENT    VARCHAR2(1000)   NOT NULL,
    REFER    NUMBER   NOT NULL,
    STEP    NUMBER   NOT NULL,
    DEPTH    NUMBER   NOT NULL,
    F_NAME    VARCHAR2(100)   ,
    DELFLAG    CHAR(1)   NOT NULL,
    REGDATE    DATE   NOT NULL,
    READCOUNT    NUMBER   NOT NULL,
    B_TYPE    CHAR(1)   NOT NULL,
    CONSTRAINT POST_PK PRIMARY KEY(SEQ),
     CONSTRAINT POST_FK FOREIGN KEY(U_ID) REFERENCES USER_U(U_ID)
);
CREATE SEQUENCE POSTBOARD_SEQ START WITH 1 INCREMENT BY 1;


INSERT INTO USER_U
(U_ID,U_PASSWORD,U_NAME,U_EMAIL,U_PHONE,U_ENABLE,U_AUTH,F_NAME)
VALUES('bbb','bbb','bbb','bb@b.com','01022224445','Y','A',NULL);

INSERT INTO HOSPITAL(
H_NAME,H_ADDRESS,H_PHONE,H_MAIL,H_REGI,U_ID,H_ENABLE,MAIN_OBJ,MAIN_ANI)
VALUES('h_na','h_addres','0103222443','h_mai','h_reg','bbb','N','001','002');

-- F 자유, R 후기, A 공지 
-- 글 입력
INSERT INTO POSTBOARD
(SEQ, U_ID, TITLE, CONTENT, REFER, STEP, DEPTH, F_NAME, DELFLAG, REGDATE, READCOUNT, B_TYPE)
VALUES(POSTBOARD_SEQ.NEXTVAL, 'jjjj','테스트2','내용',(SELECT NVL(MAX(REFER),0)+1 FROM POSTBOARD),
0,0, 'ASDD','N',SYSDATE,0,'F');

SELECT * FROM POSTBOARD ORDER BY REFER DESC, STEP ASC;

-- 글 수정
UPDATE POSTBOARD
SET TITLE='수정' , CONTENT='수정'	
WHERE SEQ='1';

-- 글 삭제
UPDATE POSTBOARD
SET DELFLAG = 'Y'
WHERE SEQ='151';

-- 다중 삭제
UPDATE POSTBOARD
SET DELFLAG = 'Y'
WHERE DELFLAG='N' AND SEQ IN ('1','2');


-- 전체 글 보기, 검색
SELECT SEQ, U_ID, TITLE, CONTENT, REFER, STEP, DEPTH, F_NAME, DELFLAG, REGDATE, READCOUNT,B_TYPE
FROM POSTBOARD
WHERE B_TYPE='F'
  AND title LIKE '%수정ㅎㅎ%'
ORDER BY REFER DESC, STEP ASC;

-- 상세 글 보기
SELECT SEQ, U_ID, TITLE, CONTENT, F_NAME, REGDATE, READCOUNT,B_TYPE
FROM POSTBOARD
WHERE SEQ='1';

-- 답글(UPDATE)
UPDATE POSTBOARD
SET STEP=STEP+1
WHERE REFER = (SELECT REFER FROM POSTBOARD WHERE SEQ='93')
AND STEP > (SELECT STEP FROM POSTBOARD WHERE SEQ='93');	

--답글 (INSERT)
INSERT INTO POSTBOARD
(SEQ, U_ID, TITLE, CONTENT, REFER, STEP, DEPTH,  DELFLAG, REGDATE, READCOUNT,B_TYPE)
VALUES(POSTBOARD_SEQ.NEXTVAL, 'jjjj', '답글', '답글작성', (SELECT REFER FROM POSTBOARD 
WHERE SEQ='93'), (SELECT STEP+1 FROM POSTBOARD WHERE SEQ = '93'), 
(SELECT DEPTH+1 FROM POSTBOARD WHERE SEQ='93'),'N',SYSDATE,0,'F');

-- 조회수 증가
UPDATE POSTBOARD
SET READCOUNT = READCOUNT +1
WHERE SEQ='1';


----------------
-- HONGBOARD

-- 글 입력
INSERT INTO HONGBOARD
(SEQ, H_REGI, U_ID, TITLE, CONTENT, REFER, STEP, DEPTH, F_NAME, DELFLAG, REGDATE, READCOUNT)
VALUES(HONGBOARD_SEQ.NEXTVAL,'h_regi','aaa','제목','내용',(SELECT NVL(MAX(REFER),0)+1 FROM HONGBOARD),
0,0, 'ASDD','N',SYSDATE,0);



-- 글 수정
UPDATE HONGBOARD
SET TITLE='수정' , CONTENT='수정'
WHERE SEQ='1';

-- 글 삭제
UPDATE HONGBOARD
SET DELFLAG = 'Y'
WHERE SEQ='1';

-- 다중 삭제
UPDATE HONGBOARD
SET DELFLAG = 'Y'
WHERE DELFLAG='N' AND SEQ IN ('1','2');


-- 답글(UPDATE)
UPDATE HONGBOARD
SET STEP=STEP+1
WHERE REFER = (SELECT REFER FROM HONGBOARD WHERE SEQ='1')
AND STEP > (SELECT STEP FROM HONGBOARD WHERE SEQ='1');	

--답글 (INSERT)
INSERT INTO HONGBOARD
(SEQ, H_REGI, U_ID, TITLE, CONTENT, REFER, STEP, DEPTH, DELFLAG, REGDATE, READCOUNT)
VALUES(HONGBOARD_SEQ.NEXTVAL, '953465279231','username', '제목이요', '답글작성', (SELECT REFER FROM HONGBOARD 
WHERE SEQ='1'), (SELECT STEP+1 FROM HONGBOARD WHERE SEQ = '1'), 
(SELECT DEPTH+1 FROM HONGBOARD WHERE SEQ='1'),'N',SYSDATE,0);

-- 조회수 증가
UPDATE HONGBOARD
SET READCOUNT = READCOUNT +1
WHERE SEQ='1';

-- 병원정보 게시판 전체글 조회 JOIN
SELECT SEQ, B.H_REGI, B.U_ID, TITLE, CONTENT, REFER, STEP, DEPTH, F_NAME, DELFLAG, REGDATE, READCOUNT
FROM HOSPITAL H JOIN HONGBOARD B ON
H.H_REGI = B.H_REGI
ORDER BY REFER DESC, STEP ASC;


-- 병원정보 게시판 상세글 조회 JOIN
SELECT SEQ, B.H_REGI, B.U_ID, TITLE, CONTENT, REFER, STEP, DEPTH, F_NAME, DELFLAG, REGDATE, READCOUNT
FROM HOSPITAL H JOIN HONGBOARD B ON H.H_REGI = B.H_REGI 
WHERE H.H_REGI = 'h_regi' AND B.SEQ='85';



SELECT SEQ, B.H_REGI, B.U_ID, TITLE, CONTENT, REFER, STEP, DEPTH, F_NAME, DELFLAG, REGDATE, READCOUNT 
FROM HOSPITAL H JOIN HONGBOARD B 
ON H.H_REGI = B.H_REGI 
WHERE H.H_REGI = TRIM(h_regi) AND B.SEQ = '85';



SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'POSTBOARD_SEQ';

ALTER SEQUENCE POSTBOARD_SEQ INCREMENT BY +1;
SELECT POSTBOARD_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE POSTBOARD_SEQ INCREMENT BY 1;


------ 병원 부분 ----------
UPDATE O_CODE SET MAIN_OBJ = REPLACE(MAIN_OBJ,' ','');

UPDATE O_CODE SET MAIN_OBJ = TRIM(MAIN_OBJ);

--select id, name, length(name)
--	from test1

SELECT LENGTH(MAIN_OBJ) FROM O_CODE;

SELECT * FROM O_CODE

SELECT TRIM(MAIN_OBJ) FROM O_CODE

DELETE FROM H_CODE_OBJ CASCADE;
DELETE FROM H_CODE_ANI CASCADE; 
DELETE FROM OBJ CASCADE;
DELETE FROM ANI CASCADE;
DELETE FROM O_CODE CASCADE;
DELETE FROM A_CODE CASCADE;

ALTER TABLE H_CODE_OBJ
MODIFY (MAIN_OBJ VARCHAR2(5));

INSERT INTO ANI (MAIN_ANI, ANI_DETAIL_CODE, ANI_CONTENT) VALUES ('가','061','잉글리쉬코카스파니엘');
INSERT INTO ANI (MAIN_ANI, ANI_DETAIL_CODE, ANI_CONTENT) VALUES ('가','049','아메리카코커스파니엘');

UPDATE HOSPITAL
		SET  H_NAME='hey사랑병원' ,  H_ADDRESS='강남구 역삼동' ,  
		H_PHONE='011' ,  H_MAIL='love@naver.com' ,  H_ENABLE = 'Y'
		WHERE H_REGI='544-34-22222';

	
 UPDATE HOSPITAL
		SET  H_NAME='동작사랑병원' ,  H_ADDRESS='서울 동작구' ,  
		H_PHONE='222' ,  H_MAIL='happy@naver.com' ,  H_ENABLE = 'Y'
		WHERE H_REGI='333-33-33333' AND U_ID='HOSPITAL3';

UPDATE HOSPITAL
		SET H_REGI='888-88-88888' WHERE U_ID='HOSPITAL3';


		

	select CONSTRAINT_NAME, TABLE_NAME, R_CONSTRAINT_NAME
from user_constraints
where CONSTRAINT_NAME = 'SYS_C0036932' 


	
	